# Generated by Django 3.2.16 on 2023-01-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameID', models.AutoField(primary_key=True, serialize=False)),
                ('P1Name', models.CharField(default='player_1', max_length=256)),
                ('P2Name', models.CharField(default='player_2', max_length=256)),
                ('Winner', models.CharField(choices=[('1', 'Player1'), ('2', 'Player2'), ('0', 'Pending')], default='0', max_length=1)),
                ('CurrPlayer', models.CharField(choices=[('0', 'None'), ('2', 'Player2'), ('1', 'Player1')], default='1', max_length=1)),
                ('P1Pos', models.IntegerField(default=0)),
                ('P2Pos', models.IntegerField(default=0)),
            ],
        ),
    ]
