# Generated by Django 3.2.16 on 2023-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='CurrPlayer',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Player1'), ('2', 'Player2')], default='1', max_length=256),
        ),
        migrations.AlterField(
            model_name='game',
            name='Winner',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Player1'), ('2', 'Player2')], default='0', max_length=1),
        ),
    ]
